language: node_js
node_js:
- '10'
dist: trusty
sudo: false
cache: yarn
notifications:
  email:
    on_success: never
deploy:
- provider: script
  script: yarn run build
  skip_cleanup: true
  on:
    branch: feature/travis-ci
- provider: firebase
  token: $FIREBASE_DEPLOY_TOKEN
  skip_cleanup: true
  on:
    branch: feature/travis-ci
