language: node_js
node_js:
- '10'
dist: trusty
sudo: false
cache: yarn
notifications:
  email:
    on_success: never
deploy:
- provider: script
  script: yarn run build
  skip_cleanup: true
  on:
    branch: feature/travis-ci
- provider: firebase
  token:
    secure: oTtwAqYEkziWAI+JBqCv3YyKq5CzQsY/hl/RAZp/qLxNMxCvrq3B8CT89Hc61wMoNvjwhPdjC6HNFbYMggbLMY2QnA/oUlBr1CS8aMlLrAESccdHggVR+3lsLLt7vVL+lx35K0rEivmUVtIP3QRHGF0QMSmaq86G4oUMtGUXszYctWw7rTFLYBGZDfRt5Kv+Bx5I2FnJNvzB2CcsyYEW/M5zqM/JYtrJjL71QzFmo5ikVDCicqy0pCBBvYMYvXNWOGWD0e8vTGnyj2eXsM+weHkh8z96ixofdKuozZfjcXa8vLEPrODIV3pKbSlqkSZ6i3yAeFK4DB43YniuJZkssKDrX5YmDNge/hQ1SpQRbVUJbg5kXY6saKz8vxWwF/JLNHjsqz1zl9fmLw2PrGmWNDndH2pqSRC5rZStshGvP0JyGtf0x9ik57whcfnXS3y/eA+iR5oUyuPBaYtSdLUgn+zzgoVFVHCPwOB0Up1PlWc5JDESSVd36OBZG0KxVdYRuTSqxTdBM2KlumlvIn58t9tXKujtFEBYDI8vl6T5gpRfmKhSMkXI2GWoEGWdv8vKDVKgzFTLcBeBg55J9OvqttrrnzK2YhfT6g4oocd4TNe5bUmzBP9joGvEhF6o8Uvc8Qp/rJa4yUx2AW/Hag+73DQ/UXEn5rfU/Bt5nniOsME=
  skip_cleanup: true
  on:
    branch: feature/travis-ci
env:
  global:
    secure: oTtwAqYEkziWAI+JBqCv3YyKq5CzQsY/hl/RAZp/qLxNMxCvrq3B8CT89Hc61wMoNvjwhPdjC6HNFbYMggbLMY2QnA/oUlBr1CS8aMlLrAESccdHggVR+3lsLLt7vVL+lx35K0rEivmUVtIP3QRHGF0QMSmaq86G4oUMtGUXszYctWw7rTFLYBGZDfRt5Kv+Bx5I2FnJNvzB2CcsyYEW/M5zqM/JYtrJjL71QzFmo5ikVDCicqy0pCBBvYMYvXNWOGWD0e8vTGnyj2eXsM+weHkh8z96ixofdKuozZfjcXa8vLEPrODIV3pKbSlqkSZ6i3yAeFK4DB43YniuJZkssKDrX5YmDNge/hQ1SpQRbVUJbg5kXY6saKz8vxWwF/JLNHjsqz1zl9fmLw2PrGmWNDndH2pqSRC5rZStshGvP0JyGtf0x9ik57whcfnXS3y/eA+iR5oUyuPBaYtSdLUgn+zzgoVFVHCPwOB0Up1PlWc5JDESSVd36OBZG0KxVdYRuTSqxTdBM2KlumlvIn58t9tXKujtFEBYDI8vl6T5gpRfmKhSMkXI2GWoEGWdv8vKDVKgzFTLcBeBg55J9OvqttrrnzK2YhfT6g4oocd4TNe5bUmzBP9joGvEhF6o8Uvc8Qp/rJa4yUx2AW/Hag+73DQ/UXEn5rfU/Bt5nniOsME=
