language: node_js

node_js:
    - '10.6.0'

dist: trusty

sudo: false

cache: yarn

notifications:
    email:
        on_success: never
        on_failure: never

branches:
  only:
    - master
    - develop

script: yarn run lint

before_deploy: yarn run build
deploy:
    - provider: firebase
      token: $FIREBASE_DEPLOY_TOKEN
      skip_cleanup: true
      on:
          branch: develop
